model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
model_type: 'llama3'
hf_token: "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"
max_tokens: 512
embeddings_path: "BAAI/bge-m3"

chat_history_path: "./chat_sessions/"
